### ISSUE TITLE
importing of existing disk images doesn't work

### ISSUE THREAD

**Issue by raharper** [raharper/mcli#4]
Example yaml
```
name: vm1
type: kvm
ephemeral: false
description:
config:
  name: vm1
  uefi: true
  tpm: true
  tpm-version: 2.0
  secure-boot: true
  disks:
      - file: jammy-server-cloudimg-amd64.img
        format: qcow2
        type: ssd
        bootindex: 0
```

Fails to correctly set the path to the existing file.
